---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

From a young age, children will spontaneously help others achieve goals. In many circumstances, however, it is unclear why exactly someone is failing to achieve a goal. In these situations, it is necessary to figure out the likely reason they are failing so that you can tailor your help accordingly. In the three experiments described in this thesis, 24- to 48-month-old children learned about three (Exp. 1) or two (Exp. 2 and 3) music toys. They then watched a confederate fail to activate a toy and request help. We varied the likely source of this confederate's failure and, in all three experiments, children were able to use their prior knowledge about the toys to target the likely source of failure. When the likely source was the toy itself, children helped by changing the toy. When the likely source was the action taken on the toy, children helped by changing the action taken on the toy.